[package]
name = "models"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
domain = { path = "../domain" }

reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
